Assign3/JobSystem/config/routes.rb
JobSystem::Application.routes.draw do
  get "search/search_results"
  resources :work_orders

  resources :workers

  root 'workers#index'

  

end

Assign3/JobSystem/app/models/work_order.rb
class WorkOrder < ActiveRecord::Base
  validates_presence_of :details, :status
  belongs_to :worker
end

Assign3/JobSystem/app/models/worker.rb
class Worker < ActiveRecord::Base
  validates_presence_of :last_name, :first_name
  has_many :work_orders
end

Assign3/JobSystem/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Assign3/JobSystem/app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search_results
    @work_orders = WorkOrder.where("status = ?", params[:search])
  end
end

Assign3/JobSystem/app/controllers/work_orders_controller.rb
class WorkOrdersController < ApplicationController
  before_action :set_work_order, only: [:show, :edit, :update, :destroy]

  # GET /work_orders
  # GET /work_orders.json
  def index
    @work_order = WorkOrder.new
    @work_orders = WorkOrder.all
  end

  # GET /work_orders/1
  # GET /work_orders/1.json
  def show
  end

  # GET /work_orders/new
  def new
    @work_order = WorkOrder.new
  end

  # GET /work_orders/1/edit
  def edit
  end

  # POST /work_orders
  # POST /work_orders.json
  def create
    @work_order = WorkOrder.new(work_order_params)
    if @work_order.save
      @work_orders = WorkOrder.all
    else
      render 'create_error'
    end

  end

  # PATCH/PUT /work_orders/1
  # PATCH/PUT /work_orders/1.json
  def update
    respond_to do |format|
      if @work_order.update(work_order_params)
        format.html { redirect_to @work_order, notice: 'Work order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @work_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_orders/1
  # DELETE /work_orders/1.json
  def destroy
    @work_order.destroy
    respond_to do |format|
      format.html { redirect_to work_orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_order
      @work_order = WorkOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_order_params
      params.require(:work_order).permit(:details, :status, :worker_id)
    end
end

Assign3/JobSystem/app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  # GET /workers
  # GET /workers.json
  def index
    @worker = Worker.new
    @workers = Worker.all
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(worker_params)
    if @worker.save
      @workers = Worker.all
    else
      render 'create_error'
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to @worker, notice: 'Worker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(:first_name, :last_name)
    end
end

Assign3/JobSystem/app/helpers/application_helper.rb
module ApplicationHelper
  def status_list
    statuses = %w{created in\ progress review created}
  end
end

Assign3/JobSystem/app/helpers/search_helper.rb
module SearchHelper
end

Assign3/JobSystem/app/helpers/work_orders_helper.rb
module WorkOrdersHelper
end

Assign3/JobSystem/app/helpers/workers_helper.rb
module WorkersHelper
end

Assign3/JobSystem/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Assign3/JobSystem/app/views/work_orders/_form.html.erb
<%= form_for(@work_order, :remote => true) do |f| %>
  <% if @work_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work_order.errors.count, "error") %> prohibited this work_order from being saved:</h2>

      <ul>
      <% @work_order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_area :details %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, options_for_select(status_list)%>
	
  </div>
  
  <div class="field">
	  <%= f.label :worker %>
	  <%= f.select :worker_id, Worker.all.map {|worker| [worker.first_name, worker.id]} %>
  </div>
  
  <div class="actions">
    <%= f.submit "Submit", :class => "btn btn-primary btn-large"%>
  </div>
<% end %>

Assign3/JobSystem/app/views/work_orders/_list_orders.html.erb
<table class = "table table-bordered table-striped table table-hover pretty">
    <tr>
	  <th>Worker</th>
      <th>Details</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <tbody>
    <% @work_orders.each do |work_order| %>
      <tr>
		<td><%= work_order.worker.first_name %> <%= work_order.worker.last_name %></td>
        <td><%= work_order.details %></td>
        <td><%= work_order.status %></td>
        <td><%= link_to 'Show', work_order %></td>
        <td><%= link_to 'Edit', edit_work_order_path(work_order) %></td>
        <td><%= link_to 'Destroy', work_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

Assign3/JobSystem/app/views/work_orders/create.js.erb
$('#orderslist').html("<%= escape_javascript(render 'list_orders') %>");
$('#orderslist').effect('highlight');

Assign3/JobSystem/app/views/work_orders/create_error.js.erb
$('#orderslist').effect('shake');
$('#error').html("<%= escape_javascript(@work_order.errors.full_messages.join(',')) %>");
$('#error').fadeIn();
setTimeout(function() { $('#error').fadeOut(); }, 2000);

Assign3/JobSystem/app/views/work_orders/edit.html.erb
<title>Edit work order</title>
<h1>Editing work_order</h1>

<%= render 'form' %>

<%= link_to 'Show', @work_order %> |
<%= link_to 'Back', work_orders_path %>

Assign3/JobSystem/app/views/work_orders/index.html.erb
<h1>Search for a Work Order</h1>
<hr>
<%= form_tag search_search_results_path, :method => 'get' do %>
	
	<%= select_tag :search, options_for_select(status_list) %>
	
    <%= submit_tag "Search", :class => "btn btn-primary btn-large" %>  
<% end %>

<br/>



<h1>Listing Work Orders</h1>
<hr>
<div id="orderslist">
	<%= render 'list_orders'%>
</div>

| <%= link_to 'Workers', workers_path %> |

Assign3/JobSystem/app/views/work_orders/new.html.erb
<title>New worker</title>
<center>
<h1>New work order</h1>

<%= render 'form' %>

<%= link_to 'Back', work_orders_path %>
</center>

Assign3/JobSystem/app/views/work_orders/show.html.erb
<title>Details for <%= @work_order.status%></title>
<center>
	<h1>Details for work order #<%= @work_order.id %> </h1>
<p id="notice"><%= notice %></p>

<br/>
<br/>

<p>
  <strong>Details:</strong>
  <%= @work_order.details %>
</p>

<p>
  <strong>Status:</strong>
  <%= @work_order.status %>
</p>

<%= link_to 'Edit', edit_work_order_path(@work_order) %> |
<%= link_to 'Back', work_orders_path %>
</center>