project/MyFacultyWebsite/config/routes.rb
MyFacultyPages::Application.routes.draw do

  get 'pages/home'
  
  resources :faculty_members do
    member do
      get 'courses'
      get 'researches'
      get 'publications'
      get 'curriculum_vitae'
      get 'contact_details'
    end
  end

  resources :sessions, :only => [ :new, :create, :destroy ]

  resources :courses, :only => [ :new, :edit, :create, :update, :destroy ]

  resources :researches, :only => [ :new, :edit, :create, :update, :destroy ]

  resources :publications, :only => [ :new, :edit, :create, :update, :destroy ]

  resources :degrees, :only => [ :new, :edit, :create, :update, :destroy ]

  resources :employments, :only => [ :new, :edit, :create, :update, :destroy ]

  resources :awards, :only => [ :new, :edit, :create, :update, :destroy ]

  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

   root 'faculty_members#index'

  

end

project/MyFacultyWebsite/app/views/layouts/_bar.html.erb
<div class='bar'>
  <% logo = image_tag('UACS.png', :alt => 'UA Computer Science', :class => 'UHCS-logo') %>
  <%= link_to logo, root_path, class: 'UHCS-path' %>
  <% if signed_in? %>
    <%= link_to 'Sign out', signout_path, method: 'delete', class: 'signin-path' %>
  <% else %>
    <%= link_to 'Sign in', signin_path, class: 'signin-path' %>
  <% end %>
</div>

project/MyFacultyWebsite/app/views/layouts/_faculty_header.html.erb
<header>
  <div class='container-fluid'>
    <div class='row-fluid'>
      <div class='span3 profile_picture'>
        <% faculty_picture = "#{@faculty_member.first_name}#{@faculty_member.last_name}.JPG" %>
        <% faculty_picture = File.exist?("app/assets/images/#{faculty_picture}") ? faculty_picture : 'rails.png' %>
        <% profile_image = image_tag(faculty_picture, :alt => 'myPhoto', :class => 'img-profile') %>

        <%= link_to profile_image, @faculty_member %>
      </div>
      <div class='banner'>
        <h1 class='header-text'>
          <%= @faculty_member.first_name %> <%= @faculty_member.last_name %>
        </h1>
        <h4 class='header-text'>
          <%= @faculty_member.position %> of <%= @faculty_member.department %>
        </h4>
      </div>
      <div class='logo-right'>
        <% ua_logo = image_tag('UA-logo-red.png', :alt => 'UA') %>
        <%= link_to ua_logo, root_path %>
      </div>
    </div>
  </div>
</header>

project/MyFacultyWebsite/app/views/layouts/_footer.html.erb
<footer>
  © 2013 University of Astalia.  All rights reserved.
</footer>

project/MyFacultyWebsite/app/views/layouts/_index_header.html.erb
<header>
  <div class='container-fluid'>
    <div class='row-fluid'>
      <div class='logo-left span3'>
         <%= image_tag('UA-logo-full.png', :alt => 'UA') %>
      </div>
      <div class='banner'>
        <h1 class='header-text'>
          University of Astalia
        </h1>
        <h4 class='header-text'>
          Department of Computer Science
        </h4>
      </div>
    </div>
  </div>
</header>

project/MyFacultyWebsite/app/views/layouts/_navigation.html.erb
<div class='span3 navigation'>
  <div class='well sidebar-nav'>
    <ul class='nav nav-list'>
      <li class='nav-header'>Navigation</li>
      <li><%= link_to 'Home', @faculty_member %></li>
      <li><%= link_to 'Courses', courses_faculty_member_path(@faculty_member) %></li>
      <li><%= link_to 'Research', researches_faculty_member_path(@faculty_member) %></li>
      <li><%= link_to 'Publications', publications_faculty_member_path(@faculty_member) %></li>
      <li><%= link_to 'Curriculum Vitae', curriculum_vitae_faculty_member_path(@faculty_member) %></li>
      <li><%= link_to 'Contact Details', contact_details_faculty_member_path(@faculty_member) %></li>
    </ul>
  </div>
</div>

project/MyFacultyWebsite/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag 'bootstrap', :media => 'all' %>
  <%= stylesheet_link_tag 'custom', :media => 'all' %>
  <%= stylesheet_link_tag 'glyphicons', :media => 'all' %>

  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='wrapper'>
    <% header = @faculty_view ? 'faculty_header' : 'index_header' %>
    <%= render "layouts/#{header}" %>

    <%= render 'layouts/bar' %>
    
    <div class='container-fluid'>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
      <div class='row-fluid'>
        <%= render 'layouts/navigation' if @faculty_member %>     
        <div class="<%= 'span9' if @faculty_view %>">
          <%= yield %>
        </div>
      </div>
    </div>

    <hr>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>