project/MyFacultyWebsite/config/routes.rb
MyFacultyPages::Application.routes.draw do

  get 'pages/home'
  
  resources :faculty_members do
    member do
      get 'courses'
      get 'researches'
      get 'publications'
      get 'curriculum_vitae'
      get 'contact_details'
    end
  end

  resources :sessions, :only => [ :new, :create, :destroy ]

  resources :courses, :only => [ :new, :edit, :create, :update, :destroy ]

  resources :researches, :only => [ :new, :edit, :create, :update, :destroy ]

  resources :publications, :only => [ :new, :edit, :create, :update, :destroy ]

  resources :degrees, :only => [ :new, :edit, :create, :update, :destroy ]

  resources :employments, :only => [ :new, :edit, :create, :update, :destroy ]

  resources :awards, :only => [ :new, :edit, :create, :update, :destroy ]

  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

   root 'faculty_members#index'

  

end

project/MyFacultyWebsite/app/models/faculty_member.rb
class FacultyMember < ActiveRecord::Base
  before_create :create_remember_token

  validates_presence_of :last_name, :first_name, :position, :department, :university_id, :email
  validates_length_of :phone, :is => 10
  validates_uniqueness_of :university_id, :phone, :email

  has_many :courses, :dependent => :destroy
  has_many :researches, :dependent => :destroy
  has_many :publications, :dependent => :destroy
  has_many :degrees, :dependent => :destroy
  has_many :employments, :dependent => :destroy
  has_many :awards, :dependent => :destroy
  
  has_secure_password

  def FacultyMember.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def FacultyMember.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
  
    def create_remember_token
      self.remember_token = FacultyMember.encrypt(FacultyMember.new_remember_token)
    end
end

project/MyFacultyWebsite/app/controllers/faculty_members_controller.rb
class FacultyMembersController < ApplicationController
  before_filter :authorize, only: [ :edit, :update ]
  before_action :set_faculty_member, except: [ :index ]
  before_action :set_faculty_view, except: [ :index ]
  before_action :correct_faculty, except: [ :index ]

  def index
    @faculty_members = FacultyMember.all
  end

  def show
    @title = "#{@faculty_member.first_name} #{@faculty_member.last_name}"
  end

  def edit
    @title = 'Edit profile'
  end
  
  def update
    respond_to do |format|
       if @faculty_member.update(faculty_member_params)
         format.html { redirect_to @faculty_member, notice: 'Successfully updated profile.' }
        format.json { head :no_content }
      else
        @title = 'Edit profile'
        format.html { render action: 'edit' }
        format.json { render json: @faculty_member.errors, status: :unprocessable_entity }
      end
     end
  end

  def courses
    @title = "Courses taught by #{@faculty_member.first_name} #{@faculty_member.last_name}"
    @courses = @faculty_member.courses.sort_by { |c| [c.year, c.term] }.reverse
  end

  def researches
    @title = "Research by #{@faculty_member.first_name} #{@faculty_member.last_name}"
    @researches = @faculty_member.researches.sort_by { |r| [r.start_date, r.end_date] }.reverse
  end

  def publications
    @title = "Publications by #{@faculty_member.first_name} #{@faculty_member.last_name}"
    @publications = @faculty_member.publications
  end

  def curriculum_vitae
    @title = "Curriculum Vitae for #{@faculty_member.first_name} #{@faculty_member.last_name}"
    @degrees = @faculty_member.degrees.sort_by { |d| d.issue_date }.reverse
    @publications = @faculty_member.publications.sort_by { |p| p.year }.reverse
    @researches = @faculty_member.researches.sort_by { |r| r.start_date }.reverse
    @employments = @faculty_member.employments.sort_by { |e| e.start_date }.reverse
    @awards = @faculty_member.awards.sort_by { |a| a.issue_date }.reverse
  end

  def contact_details
    @title = "Contact Details for #{@faculty_member.first_name} #{@faculty_member.last_name}"
  end

  private
  
    def set_faculty_member
      @faculty_member = FacultyMember.find(params[:id])
    end

    def set_faculty_view
      @faculty_view = true
    end


    def faculty_member_params
      params.require(:faculty_member).permit(:first_name, :last_name, :position, :department, :office, :phone,
        :summary, :biography)
    end
end

project/MyFacultyWebsite/app/helpers/faculty_members_helper.rb
module FacultyMembersHelper
end

project/MyFacultyWebsite/app/views/faculty_members/_form.html.erb
<%= form_for(@faculty_member) do |f| %>
  <%= render '/shared/error_messages', :object => f.object %>

  <div class='field'>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class='field'>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class='field'>
    <%= f.label :position %>
    <%= f.text_field :position %>
  </div>

  <div class='field'>
    <%= f.label :department %>
    <%= f.text_field :department %>
  </div>

  <div class='field'>
    <%= f.label :office %>
    <%= f.text_field :office %>
  </div>

  <div class='field'>
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class='field'>
    <%= f.label 'Write a short introduction about yourself:' %>
    <%= f.text_area :summary %>
  </div>

  <div class='field'>
    <%= f.label 'Add biography:' %>
    <%= f.text_area :biography %>
  </div>

  <div class='actions'>
     <%= f.submit 'Update profile', class: 'btn btn-small' %>
  </div>
<% end %>

project/MyFacultyWebsite/app/views/faculty_members/contact_details.html.erb
<div class='main_content'>
  <h2>Contact Details</h2>
  <p>
    <%= best_in_place_if signed_in?, @faculty_member, :first_name %> <%= best_in_place_if signed_in?, @faculty_member, :last_name %><br />
    University of Astalia<br />
    Department of <%= best_in_place_if signed_in?, @faculty_member, :department %><br />
    7700 University Avenue<br />
    Winston, AS 81414-1314
  </p>

  <p>
    <strong>Email: </strong>
    <%= best_in_place_if signed_in?, @faculty_member, :email%>
    <br />
    <strong>Office: </strong>
    <%= best_in_place_if signed_in?, @faculty_member, :office %>
    <br />
    <strong>Phone: </strong>
    <%= best_in_place_if signed_in?, @faculty_member, :phone %>
  </p>
</div>
<% if signed_in? %>
	<p>*Click on fields to edit*</p>
<% end %>

project/MyFacultyWebsite/app/views/faculty_members/courses.html.erb
<div class='main_content'>
  <h2>Courses</h2>
  <% @courses.each do |course| %>
    <strong>
      <%= best_in_place_if signed_in?, course, :course_no%>: <%= best_in_place_if signed_in? ,course, :name %>
    </strong>
    <p class='dates'>
		<%= best_in_place_if signed_in?, course, :term %> <%= best_in_place_if signed_in?, course, :year %>
    </p>
    <p>
    <%= best_in_place_if signed_in?, course, :summary %>
    </p>
	<%= link_to raw("<i class=\"icon-bin icon-white\"></i> Remove"), course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' if signed_in? %>
    <hr>
  <% end %>

  <% if signed_in?%>
  	<p>*Click on fields to edit*</p>
  <% end %>

  <%= link_to 'Add course', new_course_path, class: 'btn' if signed_in? %>
</div>

project/MyFacultyWebsite/app/views/faculty_members/curriculum_vitae.html.erb
<div class='main_content'>
  <h2>Curriculum Vitae</h2>

  <h3>Education</h3>
    <% @degrees.each do |degree| %>
      <div class='cv-output'>
        <strong><%= best_in_place_if signed_in?, degree, :institution %></strong><br />
        <%= best_in_place_if signed_in?, degree, :title %> <%= best_in_place_if signed_in?, degree, :field_of_study %>
        <p class='dates'>
          <%= best_in_place_if signed_in?, degree, :issue_date %>
        </p>
		<%= link_to raw("<i class=\"icon-bin icon-white\"></i> Remove"), degree, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' if signed_in? %>
      </div>
    <% end %>
    <% if signed_in? %>
		<p>*Click on fields to edit*</p>
    <% end %>
    <%= link_to 'Add degree', new_degree_path, class: 'btn btn-mini' if signed_in? %>
  <hr>

  <h3>Employment</h3>
    <% @employments.each do |employment| %>
      <div class='cv-output'>
        <strong>
        	<%= best_in_place_if signed_in?, employment, :company %>
        </strong>
        <br />
        <%= best_in_place_if signed_in?, employment, :position %>
        <p class='dates'>
        <%= best_in_place_if signed_in?, employment, :start_date %> To
        <%= best_in_place_if signed_in?, employment, :end_date %>
        </p>
        <p>
        <%= best_in_place_if signed_in?, employment, :summary %>
        </p>
		<%= link_to raw("<i class=\"icon-bin icon-white\"></i> Remove"), employment, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' if signed_in? %>
      </div>
    <% end %>
    <% if signed_in? %>
		<p>*Click on fields to edit*</p>
    <% end %>
    <%= link_to 'Add employment', new_employment_path, class: 'btn btn-mini' if signed_in? %>
  <hr>

  <h3>Publications</h3>
    <% @publications.each do |publication| %>
      <div class='cv-output'>
        <strong>
        	<%= best_in_place_if signed_in?, publication, :title %>
        </strong>
        <p class='dates'>
          <%= best_in_place_if signed_in?, publication, :year %>
        </p>
        <p>
        <%= best_in_place_if signed_in?, publication, :summary %>
        </p>
		<%= link_to raw("<i class=\"icon-bin icon-white\"></i> Remove"), publication, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' if signed_in? %>
      </div>
    <% end %>
    <% if signed_in? %>
		<p>*Click on fields to edit*</p>
    <% end %>
    <%= link_to 'Add publication', new_publication_path, class: 'btn btn-mini' if signed_in? %>
  <hr>

  <h3>Research</h3>
    <% @researches.each do |research| %>
        <div class='cv-output'>
          <strong>
            <%= best_in_place_if signed_in?, research, :topic %>
          </strong>
          <br />
          <p class='dates'>
		      <%= best_in_place_if signed_in?, research, :start_date %>	
		       To
		       <%= best_in_place_if signed_in?, research, :end_date %>	
            
          </p>
		  <%= link_to raw("<i class=\"icon-bin icon-white\"></i> Remove"), research, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' if signed_in? %>
        </div>
    <% end %>
    <% if signed_in? %>
		<p>*Click on fields to edit*</p>
    <% end %>
    <%= link_to 'Add research', new_research_path, class: 'btn btn-mini' if signed_in? %>
  <hr>

  <h3>Awards</h3>
    <% @awards.each do |award| %>
      <div class='cv-output'>
        <strong>
         <%= best_in_place_if signed_in?, award, :title %>
        </strong>
        <br />
        <%= best_in_place_if signed_in?, award, :issuer %>
        <p class='dates'>
          <%= best_in_place_if signed_in?, award, :issue_date %>
        </p>
        <p>
        <%= best_in_place_if signed_in?, award, :summary %>
        </p>
		<%= link_to raw("<i class=\"icon-bin icon-white\"></i> Remove"), award, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' if signed_in? %>
      </div>
  <% end %>
  <% if signed_in? %>
	<p>*Click on fields to edit*</p>
  <% end %>
  <%= link_to 'Add award', new_award_path, class: 'btn btn-mini' if signed_in? %>
</div>

project/MyFacultyWebsite/app/views/faculty_members/edit.html.erb
<div class='main_content'>
  <div class='row'>
    <div class='span6 offset1'>
      <h2>Update Profile</h2>
      <%= render 'form' %>
    </div>
  </div>
</div>

project/MyFacultyWebsite/app/views/faculty_members/index.html.erb
<div class='main_content'>
  <h2>Computer Science Faculty</h2>
  <table class='table table-bordered'>
    <tr>
      <th class='span2'>Photo</th>
      <th>Information</th>
      <th class='span4'>Contact Details</th>
    </tr>

    <% @faculty_members.each do |member| %>
      <tr>
        <td class='span2'>
          <% image_file = "#{member.first_name}#{member.last_name}.JPG" %>
          <% image_file = File.exist?("app/assets/images/#{image_file}") ? image_file : 'UA-logo-red.png' %>
          <%= image_tag(image_file, :class => 'img-index') %>
        </td>
        <td>
          <p>
          <strong><%= member.first_name %> <%= member.last_name %></strong><br />
          <%= member.position %><br />
          <% member.degrees.each do |degree| %>
            <%= degree.title %> <%= degree.field_of_study %>, <%= degree.institution %><br />
          <% end %>
          </p>
          <%= member.researches.pluck(:topic).to_sentence %>
          <br />
          <%= link_to 'Website', faculty_member_path(member) %>
        </td>
        <td class='span4'>
          Office: <%= member.office.blank? ? 'Unavailable' : member.office %><br />
          Phone: <%= member.phone.blank? ? 'Unavailable' : "(#{member.phone.to_s[0..2]}) #{member.phone.to_s[3..5]}-#{member.phone.to_s[6..9]}" %>
          <br />
          Email: <%= member.email %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

project/MyFacultyWebsite/app/views/faculty_members/publications.html.erb
<div class='main_content'>
  <h2>Publications</h2>
  <table class='table table-bordered'>
    <tr>
      <th class='span2'>Cover</th>
      <th>Information</th>
    </tr>

    <% @publications.each do |publication| %>
      <tr>
        <td class='span2'>
          <% image_path = publication.image_url.blank? ? 'UA-logo-red.png' : publication.image_url %>
          <%= image_tag(image_path, :class => 'img-index') %>
        </td>
        <td>
        	<strong><%= best_in_place_if signed_in?, publication, :title %> <%= best_in_place_if signed_in?, publication, :year %> </strong>
        	<p><i><%= best_in_place_if signed_in?, @faculty_member, :first_name %> <%= best_in_place_if signed_in?, @faculty_member, :last_name %></i></p>
        	<p>
            <%= best_in_place_if signed_in?, publication, :summary %>
            
          </p>
		  <%= link_to raw("<i class=\"icon-bin icon-white\"></i> Remove"), publication, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' if signed_in? %>
        </td>
      </tr>
    <% end %>
  </table>
  
  <% if signed_in?%>
  	<p>*Click on fields to edit*</p>
  <% end %>
  
  <%= link_to 'Add publication', new_publication_path, class: 'btn' if signed_in? %>
</div>
<%# best_in_place_if signed_in?, course, :summary %>

project/MyFacultyWebsite/app/views/faculty_members/researches.html.erb
<div class='main_content'>
  <h2>Research Projects</h2>
  <% @researches.each do |research| %>
    <strong><%= best_in_place_if signed_in?, research, :topic %></strong>
    <p class='dates'>
      <%= best_in_place_if signed_in?, research, :start_date %>	
       To
       <%= best_in_place_if signed_in?, research, :end_date %>	
    </p>
    <p>
    <%= best_in_place_if signed_in?, research, :summary %>
    </p>
	<%= link_to raw("<i class=\"icon-bin icon-white\"></i> Remove"), research, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' if signed_in? %>
    <hr>
  <% end %>
  
  <% if signed_in?%>
  	<p>*Click on fields to edit*</p>
  <% end %>
  
  <%= link_to 'Add research', new_research_path, class: 'btn'  if signed_in? %>
</div>

project/MyFacultyWebsite/app/views/faculty_members/show.html.erb
<div class='main_content'>
  <h2>Welcome to <%= best_in_place_if signed_in?, @faculty_member, :first_name %> <%= best_in_place_if signed_in?, @faculty_member, :last_name %>'s page!</h2>
  <p><%= best_in_place_if signed_in?, @faculty_member, :summary, type: :textarea  %></p>

  <% unless @faculty_member.biography.blank? %>
  <h4>Biography</h4>
  <p><%= best_in_place_if signed_in?, @faculty_member, :biography, type: :textarea %></p>
  <% end %>

  <% link_to raw("<i class='icon-edit'></i> Edit profile"), edit_faculty_member_path(@faculty_member), class: 'btn' if signed_in? %>
</div>
<br/>
<% if signed_in?%>
	<p>*Click on fields to edit*</p>
<% end %>