Assign4/JobSystem/config/routes.rb
JobSystem::Application.routes.draw do
  get "search/search_results"
  get "search/input_search"
  
  resources :work_orders

  resources :workers
  
  root "workers#index"

  

end

Assign4/JobSystem/app/models/work_order.rb
class WorkOrder < ActiveRecord::Base
  validates_presence_of :details, :status
  belongs_to :worker
  
  def self.search(search)
    if search
      where('status LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

Assign4/JobSystem/app/models/worker.rb
class Worker < ActiveRecord::Base
  validates_presence_of :last_name, :first_name
  has_many :work_orders
end

Assign4/JobSystem/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Assign4/JobSystem/app/controllers/work_orders_controller.rb
class WorkOrdersController < ApplicationController
  before_action :set_work_order, only: [:show, :edit, :update, :destroy]

  def index
    @work_order = WorkOrder.new
    #@work_orders = WorkOrder.all
    @work_orders = WorkOrder.search(params[:search])
  end

  def show
  end

  def new
    @work_order = WorkOrder.new
  end

  def edit
  end

  def create
    @work_order = WorkOrder.new(work_order_params)
    if @work_order.save
      @work_orders = WorkOrder.all
    end
  end

  def update
    respond_to do |format|
      if @work_order.update(work_order_params)
        format.html { redirect_to @work_order, notice: 'Work order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @work_order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @work_order.destroy
      @work_orders = WorkOrder.all
    end
  end
  
  private
    def set_work_order
      @work_order = WorkOrder.find(params[:id])
    end

    def work_order_params
      params.require(:work_order).permit(:details, :status, :worker_id)
    end
end

Assign4/JobSystem/app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  def index
    @worker = Worker.new
    @workers = Worker.all
  end

  def show
  end

  def new
    @worker = Worker.new
  end

  def edit
  end

  def create
    @worker = Worker.new(worker_params)
    if @worker.save
      @workers = Worker.all
    end
  end

  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to @worker, notice: 'Worker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @worker.destroy
      @workers = Worker.all
    end
  end

  private
    def set_worker
      @worker = Worker.find(params[:id])
    end

    def worker_params
      params.require(:worker).permit(:first_name, :last_name)
    end
end

Assign4/JobSystem/app/helpers/application_helper.rb
module ApplicationHelper
  def status_list
    statuses = %w{Created In\ Progress Review Completed}
  end
end

Assign4/JobSystem/app/helpers/search_helper.rb
module SearchHelper
end

Assign4/JobSystem/app/helpers/work_orders_helper.rb
module WorkOrdersHelper
end

Assign4/JobSystem/app/helpers/workers_helper.rb
module WorkersHelper
end

Assign4/JobSystem/app/views/workers/_form.html.erb
<%= form_for(@worker, :remote => true) do |f| %>
  <% if @worker.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(@worker.errors.count, 'error') %> prohibited this worker from being saved:</h2>

      <ul>
        <% @worker.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class='field'>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>

  <div class='field'>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>

  <div class='actions'>
    <%= f.submit "Submit", :class => "btn btn-primary btn-large" %>
  </div>
<% end %>

Assign4/JobSystem/app/views/workers/_list_workers.html.erb
<table class = "table table-bordered table-striped table table-hover pretty">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @workers.each do |worker| %>
      <tr>
        <td><%= worker.first_name %></td>
        <td><%= worker.last_name %></td>
        <td><%= link_to 'Show', worker %></td>
        <td><%= link_to 'Destroy', worker, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>

Assign4/JobSystem/app/views/workers/create.js.erb
$('#new_worker').remove();
$('#new_link').show();
$('#workerlist').html("<%= escape_javascript(render 'list_workers') %>");

Assign4/JobSystem/app/views/workers/destroy.js.erb
$('#workerlist').html("<%= escape_javascript(render 'list_workers') %>");

Assign4/JobSystem/app/views/workers/edit.html.erb
<h1>Editing worker</h1>

<%= render 'form' %>

<%= link_to 'Show', @worker %> |
<%= link_to 'Back', workers_path %>

Assign4/JobSystem/app/views/workers/index.html.erb
<center>
<h1>Listing Workers</h1>
</center>
<hr>

<center>
	<%= link_to 'New Worker', new_worker_path, id:"new_link", remote: true %>

<br/>
<hr>

<div id="workerlist">
	<%= render 'list_workers' %>
</div>

<%= link_to 'Work Orders', work_orders_path%>
</center>

Assign4/JobSystem/app/views/workers/new.html.erb
<center>
<h1>New worker</h1>

<%= render 'form' %>

<%= link_to 'Back', workers_path %>
</center>

Assign4/JobSystem/app/views/workers/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>')

Assign4/JobSystem/app/views/workers/show.html.erb
<center>
<h1>Details for <%= @worker.first_name %> <%= @worker.last_name %></h1>
<br/><br/>
<h2>Assigned Work Orders</h2>

<table class = "table table-bordered table-striped table table-hover pretty">
    <tr>
	  <th>First Name</th>
	  <th>Last Name</th>
      <th>Details</th>
      <th>Status</th>
    </tr>

  <tbody>
    <% @worker.work_orders.each do |worker| %>
      <tr>
  		<td><%= best_in_place @worker, :first_name %></td>
		<td><%= best_in_place @worker, :last_name %></td>
        <td><%= worker.details %></td>
        <td><%= worker.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</center>
<p>*Click name to edit*</p>
<br/>

<center>
<%= link_to 'Back', root_path %>
</center>